config/routes.rb
Rails.application.routes.draw do
  namespace :has_many_through do
    resources :appointments
    resources :physicians
    resources :patients
    root "appointments#index"
  end
  
  namespace :has_and_belongs_to_many do
    resources :sectors
    resources :industries
    root "industries#index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_and_belongs_to_many :industries, dependent: :destroy

    validates :name, presence: true
    validates :name,uniqueness: true
end

app/controllers/has_and_belongs_to_many/industries_controller.rb
class HasAndBelongsToMany::IndustriesController < ApplicationController
  before_action :set_industry, only: %i[ show edit update destroy ]

  # GET /industries or /industries.json
  def index
    @industries = Industry.all
  end

  # GET /industries/1 or /industries/1.json
  def show
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries or /industries.json
  def create
    @industry = Industry.new(industry_params)
    @industry.sectors << Sector.where(id: params[:industry][:sector_ids])
    respond_to do |format|
      if @industry.save
        format.html { redirect_to has_and_belongs_to_many_industry_url(@industry), notice: "Industry was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /industries/1 or /industries/1.json
  def update
    # raise "He"
    respond_to do |format|
      @industry.sectors.destroy_all
      @industry.sectors << Sector.where(id: params[:industry][:sector_ids])
      if @industry.update(industry_params)
        format.html { redirect_to has_and_belongs_to_many_industry_url(@industry), notice: "Industry was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1 or /industries/1.json
  def destroy
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to has_and_belongs_to_many_industries_url, notice: "Industry was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def industry_params
      params.require(:industry).permit(:name, :email)
    end
end

app/controllers/has_and_belongs_to_many/sectors_controller.rb
class HasAndBelongsToMany::SectorsController < ApplicationController
  before_action :set_sector, only: %i[ show edit update destroy ]

  # GET /sectors or /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1 or /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors or /sectors.json
  def create
    @sector = Sector.new(sector_params)
    @sector.industries << Industry.where(id: params[:sector][:industry_ids])
    respond_to do |format|
      if @sector.save
        format.html { redirect_to has_and_belongs_to_many_sector_url(@sector), notice: "Sector was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1 or /sectors/1.json
  def update
    @sector.industries.destroy_all
    @sector.industries << Industry.where(id: params[:sector][:industry_ids])
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to has_and_belongs_to_many_sector_url(@sector), notice: "Sector was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1 or /sectors/1.json
  def destroy
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url, notice: "Sector was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/has_and_belongs_to_many/industries_helper.rb
module HasAndBelongsToMany::IndustriesHelper
  def getIndustrySectors
    appointment = "
      <h2>Sector Details</h2>
      <div>
      <table class='table'>
      <thead class='thead-dark'>
        <tr>
          <th scope='col'>#</th>
          <th scope='col'>Sector Name</a></th>
        
        </tr>
      </thead>
      <tbody>
          #{render @industry.sectors}   
      </tbody>
      </table>
      </div>
    "
  end

  def getSectors
    sectors = Sector.all
    sectors.map{|sector| [sector.name,sector.id]}
  end
end

app/helpers/has_and_belongs_to_many/sectors_helper.rb
module HasAndBelongsToMany::SectorsHelper
    def getSectorsIndustries
        appointment = "<h2>Industries Details</h2>
            <div>
            <table class='table'>
            <thead class='thead-dark'>
                <tr>
                <th scope='col'>#</th>
                <th scope='col'>Physician Name</th>
                <th scope='col'>Patient Name</th>
                <th scope='col'>Apointment Date</th>
                
                </tr>
            </thead>
            <tbody>
                #{render @sector.industries}   
            </tbody>
            </table>
            </div>"
    end

    def getIndustries
        industries = Industry.all
        industries.map{|industry| [industry.name,industry.id]}
    end
end

app/views/has_and_belongs_to_many/sectors/_form.html.erb
<%= form_with(model: sector, url: {action: action}) do |form| %>
  <% if sector.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
        <% sector.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <% getIndustries.each do |industry|%>
      <%= form.check_box :industry_ids, {multiple: true}, industry[1], false%>
      <%= form.label industry[0]%>
    <% end%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/has_and_belongs_to_many/sectors/_sector.html.erb
<tr id="<%= dom_id sector %>">
  <th scope="row"><%= sector.id %></th>
  <td><%= link_to sector.name, has_and_belongs_to_many_sector_path(sector)%></td>
  <% if defined?(show)%>
    <td><%= sector.industries.count %></td>
  <%end%>
  <% if defined?(action) %>
    <td>
      <div class="d-inline-flex">
      <%= link_to "Show", has_and_belongs_to_many_sector_path(sector), class: "btn btn-info" if defined?(show) %>
      <%= link_to "Edit", edit_has_and_belongs_to_many_sector_path(sector), class: "btn btn-success"%>
      <%= button_to "Destroy", has_and_belongs_to_many_sector_path(sector), method: :delete, class: "btn btn-danger", form: {data: { turbo_confirm: 'Are you sure?' } }%>
      </div>
    </td>
  <%end%>
</tr>

app/views/has_and_belongs_to_many/sectors/edit.html.erb
<h1>Editing sector</h1>

<%= render "form", sector: @sector, action: "update" %>

<br>

<div>
  <%= link_to "Show this sector", has_and_belongs_to_many_sector_path(@sector) %> |
  <%= link_to "Back to sectors", has_and_belongs_to_many_sectors_path %>
</div>

app/views/has_and_belongs_to_many/sectors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sectors</h1>

<%= link_to "New sector", new_has_and_belongs_to_many_sector_path %>

<div id="sectors">

  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Sector Name</th>
          <th scope="col">Total Industries</th>
          <th scope="col">Action</th>
          
        </tr>
      </thead>
      <tbody>
      <% @sectors.each do |sector| %>
        <%= render "sector", sector: sector, show: "true", action: true%>
      <% end%>
      </tbody>
  </table>
</div>

app/views/has_and_belongs_to_many/sectors/new.html.erb
<h1>New sector</h1>

<%= render "form", sector: @sector, action: "create" %>

<br>

<div>
  <%= link_to "Back to sectors", sectors_path %>
</div>

app/views/has_and_belongs_to_many/sectors/show.html.erb
<h2>Sector Details</h2>
<p style="color: green"><%= notice %></p>
<div id="sectors">

  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Sector Name</th>
          <th scope="col">Action</th>
          
        </tr>
      </thead>
      <tbody>
        <%= render "sector", sector: @sector, action: true %>
      </tbody>
  </table>
</div>

<%= getSectorsIndustries.html_safe %>