config/routes.rb
Rails.application.routes.draw do
  namespace :has_many_through do
    resources :appointments
    resources :physicians
    resources :patients
    root "appointments#index"
  end
  
  namespace :has_and_belongs_to_many do
    resources :sectors
    resources :industries
    root "industries#index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :appointment_date, presence: true

  belongs_to :physician
  belongs_to :patient
end

app/controllers/has_many_through/appointments_controller.rb
class HasManyThrough::AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to has_many_through_appointment_url(@appointment), notice: "Appointment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to has_many_through_appointment_url(@appointment), notice: "Appointment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_appointments_url, notice: "Appointment was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:appointment_date, :patient_id, :physician_id)
    end
end

app/controllers/has_many_through/patients_controller.rb
class HasManyThrough::PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to has_many_through_patient_url(@patient), notice: "Patient was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to has_many_through_patient_url(@patient), notice: "Patient was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_patients_url, notice: "Patient was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/controllers/has_many_through/physicians_controller.rb
class HasManyThrough::PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to has_many_through_physician_url(@physician), notice: "Physician was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to has_many_through_physician_url(@physician), notice: "Physician was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_physicians_url, notice: "Physician was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
  params.require(:physician).permit(:name, :email)
    end
end

app/helpers/has_many_through/appointments_helper.rb
module HasManyThrough::AppointmentsHelper
    def getPhysicians
        physicians = Physician.all
        physicians.map{|physician| [physician.name,physician.id]}
    end

    def getPatients
        patients = Patient.all
        patients.map{|patient| [patient.name,patient.id]}
    end
end

app/helpers/has_many_through/patients_helper.rb
module HasManyThrough::PatientsHelper

    def getApointmentPatient 
        appointment = "<h2>Apointment Details</h2>
            <div>
            <table class='table'>
            <thead class='thead-dark'>
                <tr>
                <th scope='col'>#</th>
                <th scope='col'>Physician Name</th>
                <th scope='col'>Patient Name</th>
                <th scope='col'>Email</th>
                <th scope='col'>Action</th>
                
                </tr>
            </thead>
            <tbody>
                #{render @patient.appointments}   
            </tbody>
            </table>
            </div>"
    end
end

app/helpers/has_many_through/physicians_helper.rb
module HasManyThrough::PhysiciansHelper
    def getApointmentPhysician 
        appointment = "<h2>Apointment Details</h2>
            <div>
            <table class='table'>
            <thead class='thead-dark'>
                <tr>
                <th scope='col'>#</th>
                <th scope='col'>Physician Name</th>
                <th scope='col'>Patient Name</th>
                <th scope='col'>Apointment Date</th>
                <th scope='col'>Action</th>
                
                </tr>
            </thead>
            <tbody>
                #{render @physician.appointments}   
            </tbody>
            </table>
            </div>"
    end
end

app/views/has_many_through/appointments/_appointment.html.erb
<tr id="<%= dom_id appointment %>">
  <th scope="row"><%= appointment.id %></th>
  <td><%= link_to appointment.physician.name, has_many_through_physician_path(appointment.physician, show_apointment: false) %></td>
  <td><%= link_to appointment.patient.name, has_many_through_patient_path(appointment.patient, show_apointment: false) %></td>
  <td><%= appointment.appointment_date %></td>
  <td>
    <div class="d-inline-flex">
    <%= link_to "Show", has_many_through_appointment_path(appointment), class: "btn btn-info" if defined?(show) %>
    <%= link_to "Edit", edit_has_many_through_appointment_path(appointment), class: "btn btn-success"%>
    <%= button_to "Destroy", has_many_through_appointment_path(appointment), method: :delete, class: "btn btn-danger", form: {data: { turbo_confirm: 'Are you sure?' } }%>
    </div>
  </td>
</tr>

app/views/has_many_through/appointments/_form.html.erb
<%= form_with(model: appointment, url: {action: action}) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  </div>

  <div>
    <%=form.select(:physician_id,getPhysicians)%>
  <div>
    <%=form.select(:patient_id,getPatients)%>
  </div>
  <div>
    <%= form.label :appointment_date, style: "display: block" %>
    <%= form.date_field :appointment_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/has_many_through/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment, action: "update" %>

<br>

<div>
  <%= link_to "Show this appointment", has_many_through_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", has_many_through_appointments_path %>
</div>

app/views/has_many_through/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<%= link_to "New appointment", new_has_many_through_appointment_path %>
<div id="appointments">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Physician</th>
        <th scope="col">Patient</th>
        <th scope="col">Appointment date</th>
        <th scope="col">Action</th>
        
      </tr>
    </thead>
    <tbody>
    <% @appointments.each do |appointment| %>
      <%= render "appointment", appointment: appointment, show: "true"%>
     <% end%>
    </tbody>
  </table>
</div>

app/views/has_many_through/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment, action: "create" %>

<br>

<div>
  <%= link_to "Back to appointments", has_many_through_appointments_path %>
</div>

app/views/has_many_through/appointments/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Appointment</h1>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Physician</th>
        <th scope="col">Patient</th>
        <th scope="col">Appointment date</th>
        <th scope="col">Action</th>
        
      </tr>
    </thead>
    <tbody>
      <%= render @appointment %>
    </tbody>
  </table>