config/routes.rb
Rails.application.routes.draw do
  namespace :has_many_through do
    resources :appointments
    resources :physicians
    resources :patients
    root "appointments#index"
  end
  
  namespace :has_and_belongs_to_many do
    resources :sectors
    resources :industries
    root "industries#index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/physician.rb
class Physician < ApplicationRecord
	before_create :generate_unique_id
	
	validates :name, :email, presence: true
	validates :unique_id, uniqueness: true
	validates :email, format: { with: /\A[a-zA-Z0-9.!\#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\z/, 
				message: " invalid"  }, 
				uniqueness: { case_sensitive: false }, 
				length: { minimum: 4, maximum: 254 }

	has_many :appointments
	has_many :patients, through: :appointments
	private
			def generate_unique_id
					loop do
							unique_id = "P-"+SecureRandom.hex(3)+"-"+SecureRandom.hex(2).to_i(16).to_s+"-"+SecureRandom.hex(3)
							skip if unique_id.size != 21
							self.unique_id = unique_id
							break unless Physician.exists?(unique_id: unique_id)
					end
			end
end

app/controllers/has_many_through/appointments_controller.rb
class HasManyThrough::AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to has_many_through_appointment_url(@appointment), notice: "Appointment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to has_many_through_appointment_url(@appointment), notice: "Appointment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_appointments_url, notice: "Appointment was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:appointment_date, :patient_id, :physician_id)
    end
end

app/controllers/has_many_through/patients_controller.rb
class HasManyThrough::PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to has_many_through_patient_url(@patient), notice: "Patient was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to has_many_through_patient_url(@patient), notice: "Patient was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_patients_url, notice: "Patient was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/controllers/has_many_through/physicians_controller.rb
class HasManyThrough::PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to has_many_through_physician_url(@physician), notice: "Physician was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to has_many_through_physician_url(@physician), notice: "Physician was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to has_many_through_physicians_url, notice: "Physician was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
  params.require(:physician).permit(:name, :email)
    end
end

app/helpers/has_many_through/appointments_helper.rb
module HasManyThrough::AppointmentsHelper
    def getPhysicians
        physicians = Physician.all
        physicians.map{|physician| [physician.name,physician.id]}
    end

    def getPatients
        patients = Patient.all
        patients.map{|patient| [patient.name,patient.id]}
    end
end

app/helpers/has_many_through/patients_helper.rb
module HasManyThrough::PatientsHelper

    def getApointmentPatient 
        appointment = "<h2>Apointment Details</h2>
            <div>
            <table class='table'>
            <thead class='thead-dark'>
                <tr>
                <th scope='col'>#</th>
                <th scope='col'>Physician Name</th>
                <th scope='col'>Patient Name</th>
                <th scope='col'>Email</th>
                <th scope='col'>Action</th>
                
                </tr>
            </thead>
            <tbody>
                #{render @patient.appointments}   
            </tbody>
            </table>
            </div>"
    end
end

app/helpers/has_many_through/physicians_helper.rb
module HasManyThrough::PhysiciansHelper
    def getApointmentPhysician 
        appointment = "<h2>Apointment Details</h2>
            <div>
            <table class='table'>
            <thead class='thead-dark'>
                <tr>
                <th scope='col'>#</th>
                <th scope='col'>Physician Name</th>
                <th scope='col'>Patient Name</th>
                <th scope='col'>Apointment Date</th>
                <th scope='col'>Action</th>
                
                </tr>
            </thead>
            <tbody>
                #{render @physician.appointments}   
            </tbody>
            </table>
            </div>"
    end
end

app/views/has_many_through/physicians/_form.html.erb
<%= form_with(model: physician, url:{action: action}) do |form| %>
  <% if physician.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
        <% physician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/has_many_through/physicians/_physician.html.erb
<tr id="<%= dom_id physician %>">
  <th scope="row"><%= physician.id %></th>
  <td><%= physician.name%></td>
  <td><%= physician.email %></td>
  <td><%= physician.unique_id %></td>
  <% if defined?(show)%>
    <td><%= physician.appointments.count %></td>
  <%end%>
  <td>
    <div class="d-inline-flex">
    <%= link_to "Show", has_many_through_physician_path(physician), class: "btn btn-info" if defined?(show) %>
    <%= link_to "Edit", edit_has_many_through_physician_path(physician), class: "btn btn-success"%>
    <%= button_to "Destroy", has_many_through_physician_path(physician), method: :delete, class: "btn btn-danger", form: {data: { turbo_confirm: 'Are you sure?' } }%>
    </div>
  </td>
</tr>

app/views/has_many_through/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render "form", physician: @physician, action: "update" %>

<br>

<div>
  <%= link_to "Show this physician", has_many_through_physician_path(@physician) %> |
  <%= link_to "Back to physicians", has_many_through_physicians_path %>
</div>

app/views/has_many_through/physicians/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Physicians</h1>

<%= link_to "New physician", new_has_many_through_physician_path %>
<div id="physicians">

  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">physician Name</th>
          <th scope="col">Email</th>
          <th scope="col">Unique Id</th>
          <th scope="col">Total Apointments</th>
          <th scope="col">Action</th>
          
        </tr>
      </thead>
      <tbody>
      <% @physicians.each do |physician| %>
        <%= render "physician", physician: physician, show: "true"%>
      <% end%>
      </tbody>
  </table>
</div>

app/views/has_many_through/physicians/new.html.erb
<h1>New physician</h1>

<%= render "form", physician: @physician, action: "create" %>

<br>

<div>
  <%= link_to "Back to physicians", has_many_through_physicians_path %>
</div>

app/views/has_many_through/physicians/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Physician Details</h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Physician Name</th>
      <th scope="col">Email</th>
      <th scope="col">Unique Id</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @physician%>
  </tbody>
</table>

<%= getApointmentPhysician.html_safe unless params[:show_apointment].present? && params[:show_apointment] == 'false' %>