config/routes.rb
Rails.application.routes.draw do
  namespace :has_many_through do
    resources :appointments
    resources :physicians
    resources :patients
    root "appointments#index"
  end
  
  namespace :has_and_belongs_to_many do
    resources :sectors
    resources :industries
    root "industries#index"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/views/layouts/_nav_has_and_belongs_to_many.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
      <%= link_to "Home", root_path, class:"navbar-brand text-white"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Industries", has_and_belongs_to_many_industries_path, class:"nav-link text-white"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sectors", has_and_belongs_to_many_sectors_path, class:"nav-link text-white"%>
          </li> 
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_nav_has_many_through.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
      <%= link_to "Home", root_path, class:"navbar-brand text-white"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Apointments", has_many_through_appointments_path, class:"nav-link text-white"%>
          </li>
          <li class="nav-item">
            <%= link_to "Physicians", has_many_through_physicians_path, class:"nav-link text-white"%>
          </li>
          <li class="nav-item">
            <%= link_to "Patient", has_many_through_patients_path, class:"nav-link text-white"%>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if controller.class.name.split("::").first=="HasManyThrough"%>
      <%= render "layouts/nav_has_many_through"%>
    <% elsif controller.class.name.split("::").first=="HasAndBelongsToMany"%>
      <%= render "layouts/nav_has_and_belongs_to_many"%>
    <%end %>
    <%= yield %>
  </body>
</html>